### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Funmungus** [hluk/imagequick#1]
Hellooo.  What is the licensing for this?  I may want to incorporate it in an Android app for decks of cards.  Attribution and link is possible.

**Comment by hluk** [comment]
I haven't touched the code in more than 5 years and I'm not using the app anymore. It possibly no longer works well with current versions of Qt.

So unless you are willing to make some code fixes yourself I suggest you look elsewhere.

Anyway, I would be OK with any open source license that works with Qt.

**Comment by Funmungus** [comment]
Thanks. I don't think compatibility will be a problem. If my own project makes any money I might come back and do it, and probably add pinch to zoom at the same time.
